### ISSUE TITLE
Huge CPU Usage on certain sites

### ISSUE THREAD

**Issue by Liz-chan** [lykahb/sticky-ducky#10]
How to reproduce:

1. Go to https://dis.cool or https://dis.cool/users/ with the extension enabled
2. Click on the "users" tab, or if already on the users tab, click one of the users.
3. Look at the CPU usage of the extension along with it doing this and this:
https://streamable.com/omgsf and https://streamable.com/p9qxh

**Comment by lykahb** [comment]
Thank you for the report. I just released 1.3. It has smarter handling of style sheet failures and a few other optimizations.

**Comment by Liz-chan** [comment]
Seems to have worked perfectly, thanks.
