### ISSUE TITLE
Doesn't seem to work on https://html-agility-pack.net

### ISSUE THREAD

**Issue by HubKing** [lykahb/sticky-ducky#20]
For example, on this page ( https://html-agility-pack.net/select-nodes ), the font is too small, so I zoomed the page in using Ctrl+wheel, and the useless thick top bar took a lot of space. When I scrolled the page, it did not disappear when Sticky Ducky is enabled. Maybe it is worth to investigate why Sticky Ducky cannot hide this top bar.

**Comment by lykahb** [comment]
I cannot reproduce this. Please let me know if the problem still exists.
