### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by binury** [lykahb/sticky-ducky#21]
Howdy

`sticky-ducky` hides the parallax for [this webpage](https://dottid.com/product-index)

I'm very curious to know what the criterion for the match is in this case? Or what exemption was withheld from these benign `fixed` elements?

On a side note, the "show on: hover" option doesn't seem to work in this case either. 🤔

**Comment by binury** [comment]
> the "show on: hover" option doesn't seem to work in this case either

Interestingly, it does work toward the very bottom of the page…

**Comment by binury** [comment]
I have noticed that these elements will sporadically hide/show upon refresh. Seems like it could be due to the [classification](https://github.com/lykahb/sticky-ducky/blob/05b79bc78f370fd1e1492e3b3ca72d1c22eae198/src/js/content.js#L175-L196) of the `fixed` elements which might(!) have changing attributes at load-time

![image](https://user-images.githubusercontent.com/1146921/124026123-e5f13e80-d9b6-11eb-9930-4390c7537fa7.png)

(In the case of this webpage, the expected classification would be `splash`, which would be a true negative)

**Comment by lykahb** [comment]
Classification of an element is an expensive operation. For better performance and energy savings it is only done once.

Sticky elements that change their dimensions and position are going to confuse the extension. Unfortunately, there is no fix for that. I would recommend adding this website to the whitelist.

**Comment by binury** [comment]
It might be efficient to reclassify in response to an Event trigger via [ResizeObserver](https://web.dev/resize-observer)
