### ISSUE TITLE
Causes additional animation on Tumblr

### ISSUE THREAD

**Issue by MarjaE2** [lykahb/sticky-ducky#22]
Set Sticky Ducky to "On top of the page"

Visit https://www.tumblr.com/dashboard

Something appears at the bottom of the page, animates moving to the top, and is then readable saying "Now, where were we?"

https://user-images.githubusercontent.com/12875862/125683668-ccfe6c0c-c2a3-45b9-a1c6-44eb5f6a6dc7.mov

Screenshot in Firefox 88, with font switches, high contrast mode, reduce motion, etc.

**Comment by MarjaE2** [comment]
At 4 seconds in, 1 frame catches it as it crosses the row of icons.

**Comment by lykahb** [comment]
Sticky Ducky does not add any animations to the page. It is possible that Tumblr reacts to it adding an attribute to a header by re-rendering it, but that's unlikely. Does it behave the same way when Sticky Ducky is in Disabled mode or the website is whitelisted?
