### ISSUE TITLE
Can't un-whitelist a website

### ISSUE THREAD

**Issue by MarjaE2** [lykahb/sticky-ducky#23]
1. Go into settings.
2. Remove the website from the list.
3. Leave the pop-up.
4. Go into settings again.
5. Check the list-- it's back!
6. Hit enter. Just get an extra line.
7. Leave the pop-up.
8. Go into settings again.
9. Check the list-- it's back again!

**Comment by MarjaE2** [comment]
Using Firefox 88.

**Comment by lykahb** [comment]
Do you leave the popup by clicking outside of it? Do you click "Save" after editing the whitelist?

**Comment by MarjaE2** [comment]
Where would I click "Save"?
![Screen Shot 2021-07-28 at 8 27 33 AM](https://user-images.githubusercontent.com/12875862/127322179-c46d5d36-0f37-4d45-b275-e218b3bfc628.png)

**Comment by lykahb** [comment]
On your screenshot the font is too large. It makes the content larger than the popup, so the buttons are hidden below the text area. Do you have any settings for fonts or the Firefox user interface? I'd like to reproduce this.

**Comment by MarjaE2** [comment]
In about:preferences, I set Andika 20 for all fonts, minimum font size 20, do not let sites override.

In userChrome.css and userContent.css I use

/* Global UI font */
* { font-family: Andika !important; }
* { font-size: 16pt !important; }
* { text-shadow:none !important; }

It's probably not possible to tweak an add-on for every font size option. In Firefox, I've requested an enhancement to let users resize the pop-up menus:

https://bugzilla.mozilla.org/show_bug.cgi?id=1722431
