### ISSUE TITLE
Does not work on https://developer.android.com/codelabs

### ISSUE THREAD

**Issue by HubKing** [lykahb/sticky-ducky#26]
For example, https://developer.android.com/codelabs/jetpack-compose-basics#0

The top bar does not go away.

![image](https://user-images.githubusercontent.com/10900489/147154018-6c8b0bc0-d804-49e0-8116-f0aacfe7b2da.png)

**Comment by lykahb** [comment]
Thank you for the report. Unfortunately, that bar is not a fixed element. The scrollbar starts below the top of the page, which means that the content is inside of a smaller scrollable area below the header.

Remaking layouts is a much more complex and error-prone task than hiding the fixed and sticky elements, and it is out of scope for Sticky Ducky.
