### ISSUE TITLE
Fails to work on Facebook.com

### ISSUE THREAD

**Issue by jputting** [lykahb/sticky-ducky#31]
Hi,
I amusing Sticky Ducky Version 1.7.2

It installed in the Brave Browser Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64](https://brave.com/latest/) 

When I use facebook.com this extension fails to remove a horizontal bar which first appears at the top of the webpage and is used for search and provides other information about the posters page.

This horizontal bar follows you down screen as you scroll and obscuring parts of the webpage.

I would prefer to have that useful horizontal bar remain at the top of screen and not follow me down the page as  I scroll.

I have tried all the various Sticky Ducky settings and it completely fails to block this very annoying horizontal bar.

<img width="1024" alt="Screen Shot 2022-09-17 at 3 45 35 am" src="https://user-images.githubusercontent.com/10370101/190705715-278e21fe-c86c-4907-a5d6-502ae942f3c5.png">

**Comment by jputting** [comment]
I would really like this extension to function properly on facebook and hide that annoying horizontal bar.

Disabling Sticky Ducky would simply mean I am still being annoyed by that horizontal bar which follows me down the webpage  and obscures part of the content.

It would be appreciated if the developer of Sticky Ducky could devote some time and try to discover why it is failing on facebook.

I hope this get fixed very soon.

**Comment by lykahb** [comment]
I appreciate how detailed the report is. There are a few known scenarios where Sticky Ducky cannot distinguish a useful element from a fixed one and makes a more cautious choice of not hiding it. I'd recommend installing an adblocker like uBlock Origin and zapping the bar.

**Comment by jputting** [comment]
Zapping the horizontal bar is simply NOT a viable option as this horizontal bar provides useful features such as searching that users facebook content and other information about the creator of that facebook page.

I simply do NOT want that horizontal bar following me down the facebook page and obscuring content on the webpage.

Sticky Duck has options to pin these types of bars to the top of the webpage and prevent them following you down the page as you scroll, another option is to have them appear when hovering over them, or have them appear when scrolling up or at the top of the webpage

**Comment by jputting** [comment]
I also understand your reasons not for hiding features which may be useful.

Your Sticky Duck is designed to allow hidden features to be revealed when hovering over them or appear after scrolling up and also you can choose to have them appear at the top of the webpage.

If you can make Sticky Ducky work on facebook, the option to have that horizontal bar appear at the top of the page or when hovering over it would allow users of facebook to still use all of its functionality.

It should simply prevent this horizontal bar getting in front of the webpage content and obscuring parts of it.

Please reconsider your decisions and try to get Sticky Duck working on facebook.

**Comment by lykahb** [comment]
I think that this issue indicates that that an FAQ would be useful. Let me know if this clarifies the issue. What you ask is reasonable but there are technical constraints for that. I don't really use facebook but this bar shares the same issue with the github file pane I described below.

### How does Sticky Ducky work? At a high level:
1. It analyzes style sheets to discover rules that make elements fixed or sticky.
2. Then it uses selectors from them to find the sticky elements in the page DOM.
3. For each element that may be sticky, apply heuristics to classify its type (header, footer, etc.) and decide if it should be hidden and under what conditions.

### The page still has a sticky element
Likely, Sticky Ducky has detected that element but its heuristics decided not to hide it. You can use developer tools to see if it found it - the detected elements would have an extra attribute `sticky-ducky-type`.

### Why not hide everything sticky?
Cleaning up sticky elements too eagerly can break websites. Even worse, it would not be obvious that the extension has caused it and the site needs to be whitelisted. So the heuristics make cautious choices.
Here are a few examples:
- On Twitter (and many other sites) opening a picture full-screen brings up a gallery view and disables scroll on the page. The gallery itself is sticky. So hiding it would create an impression that the page froze and does not respond.
- On Github on PR files view the bars with file names are sticky. Ideally, we want to show them when they are in the middle of the screen and hide when they should be scrolled away. Alas the browsers support the [`:stuck` pseudoclass](https://github.com/w3c/csswg-drafts/issues/1656), we cannot distinguish those cases. So there is only a choice between hiding them in any position or doing nothing.

**Comment by jputting** [comment]
I fully understand that the Sticky Ducky Heuristics can be cautious and decide not to block a sticky page element.

However as the developer you are obviously fully aware of all the Sticky Ducky options for "When To Show Elements":

1. When hovering over a sticky element.

2. After scrolling up.

3. On top of the page.

4. Always (Disable the extension)

You also have added a White List to prevent the blocking of elements on specific webpages.

When those options used on a problematic website they will fix any problem where Sticky Ducky blocks something it should not block.

Could you possibly introduce an option for "Strict Blocking" of sticky elements which would enforce more aggressive rules in blocking sticky elements.

This feature would only be manually enabled on problematic websites where the normal level of Sticky Ducky blocking fails and that option would need to be labelled with a very clear warning about possible website breakage.

The Sticky Ducky toolbar button should also badged with a count of the things blocked along with a change in colour to clearly indicate it is actively blocking things on that webpage.

In my experience there are far too many websites where the Sticky Ducky heuristics are allowing far too much extremely annoying and useless garbage to remain onscreen untouched.

**Comment by jputting** [comment]
Perhaps the developer could possibly take a look at PopUpOff, that extension is far superior to Sticky Ducky.

It has 3 different default modes of usage, Dormant, Moderate and Aggressive. You can also configure it to use a particular mode of operation for each individual website. 

If this was implemented the combination of the best features of Sticky Ducky and PopUpOff would give users the very best ability to block annoying garbage with simple easy to use control.

As mentioned before there is a need for the Sticky Ducky toolbar icon to be badged with the number of things blocked and a colour change to indicate if it is active or dormant.

The Sticky Ducky built in Heuristics are missing far too much annoying garbage on too many websites.

**Comment by lykahb** [comment]
It is nice to have a bug report with details and potential solutions. However, this is not a paid product with priority support, so please set your expectations accordingly. Nudging an open-source developer with "need", "devote time" and "very soon" would not speed up anything.
 
The changes you suggest are reasonable, however I do not have time for active development. The pull requests are welcome. For adjusting the heuristics, instead of dormant/moderate/aggressive modes, it would be more flexible to have per-site settings for hiding footer/header/everything.

I am glad that you found a solution that works better for you.
