### ISSUE TITLE
Not working.... 

### ISSUE THREAD

**Issue by Sbrjt** [lykahb/sticky-ducky#33]
This [site](https://www.khanacademy.org/computing/computer-programming/html-css/web-development-tools/a/hosting-your-website-on-github) has got sticky headers and footers but the add-on isn't doing its job :(

<img src="https://github.com/lykahb/sticky-ducky/assets/83166133/4b0287a2-e909-4557-af9f-6b8ea37b6baf" height="200">

Can you please fix it?

**Comment by lykahb** [comment]
Technically, those are not sticky elements. Instead, the scrollable viewport is a sibling of a layout together with header and footer.

There is no automated way to recognize that layout and clean it up. I'd recommend deleting those elements with ublock.
