### ISSUE TITLE
Twitter is broken due to fallback nav behavior

### ISSUE THREAD

**Issue by binury** [lykahb/sticky-ducky#5]
[Will edit post to add more details]

**Comment by binury** [comment]
![2018-09-01 12_08_02-people followed by eric hagen erichagen8 _ twitter](https://user-images.githubusercontent.com/1146921/44948243-c50bd780-addf-11e8-84b8-45a43b541f40.png)

**Comment by lykahb** [comment]
Can you give the details about your browser and the mode of sticky ducky?

**Comment by lykahb** [comment]
To start investigation on this, I will need description of what's wrong on the screenshot, expected result and steps to reproduce.

**Comment by lykahb** [comment]
Closing as there are no updates.
