### ISSUE TITLE
Whitelist Option Needed

### ISSUE THREAD

**Issue by jputting** [lykahb/sticky-ducky#7]
Sticky-ducky is a good Firefox add-on for controlling those annoying sticky page elements on websites that follow you down a page and obscure text.

However sticky-ducky can create issues on certain websites and even if I try every available setting in the sticky-duck configuration the problems can still persist and make the website unusable unless I disable sticky-ducky completely.

A quite simple solution to this issue would be to have an option to Whitelist a website would save the developer the time and trouble of trying to determine the source of the trouble.

Another excellent suggestion would be to try and force those sticky page elements to stay in their original position.

I do hope the developer of this add-on can implement these much needed enhancements to sticky-ducky as soon as possble.

**Comment by lykahb** [comment]
The whitelist is available in settings of the recent version 1.2.

**Comment by jputting** [comment]
Hi,

Many thanks for adding that option, it will save you the time and effort of trying to figure out why  stickyducky causes issues on some websites no matter what setting is used.

I feel it should be labelled as "Add To Whitelist" to make it quite clear there is that option available, simply having it labeled as "Settings" could result in people overlooking that option and needlesly complaining about it.

**Comment by lykahb** [comment]
Right, putting the word whitelist on it is a good idea. I'll rename it back to settings once there are more options.

**Comment by jputting** [comment]
Hi,

In the future would it be possible to have an option to simply add the current website/domain to the Whitelist via a drop down menu? 

That would help to ensure that the correct format for website/domain is used and avoid complaints about the stickyducky whitelist not functioning.

**Comment by lykahb** [comment]
The UI is following the UI of adblockers. I try to keep it simple. The format in the simplest form just describes a substring of URL, so there is little chance to get things wrong.
