### ISSUE TITLE
Allow setting isDevelopment to false

### ISSUE THREAD

**Issue by ghost** [lykahb/sticky-ducky#8]
In the Firefox extension, there currently is no option/setting to change the value of isDevelopment, so a number of lines are added to the console log:
```
Sticky Ducky:  Call to exploreStylesheets took 2ms
Sticky Ducky:  exploredStickies Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
Sticky Ducky:  Call to exploreStickies took 1ms
Sticky Ducky:  Call to reviewStickies took 1ms
Sticky Ducky:  Call to exploreStylesheets took 2ms
Sticky Ducky:  exploredStickies Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
...etc
```
It's a minor issue, but when tracking down errors on a page, it's extra visual noise. It looks like there's a platform file for Safari that allows setting isDevelopment, but nothing in popup.html/popup.js to toggle this value.

**Comment by ghost** [comment]
May not be an issue, I found my good-enough workaround.

1. Get internal extension UUID from about://debugging
2. Open the settings page: moz-extension://<UUID>/popup.html
3. (This will wipe out the whitelist, so copy it first if you have something set.)
Open developer console, and paste in:
vAPI.sendToBackground('updateSettings', {whitelist: '', isDevelopment: false}); 
4. Restart Firefox or disable/enable extension (may not be necessary).

**Comment by lykahb** [comment]
Thank you for the report. That got committed by mistake. By default `isDevelopment` should be false.

**Comment by lykahb** [comment]
Fixed in the recent version.
